Vet clinic database: create animals table
shihabrafio/Vet-Clinic pull request #1
Opened 2023-07-10 16:58 UTC by shihabrafio

Create a database named vet_clinic.
Create a table named animals with the following columns:
- id: integer
- name: string
- date_of_birth: date
- escape_attempts: integer
- neutered: boolean
- weight_kg: decimal

- Insert the following data:
  
   - Animal: His name is Agumon. He was born on Feb 3rd, 2020, and currently weighs 10.23kg. He was neutered and he has never tried to escape.
   - Animal: Her name is Gabumon. She was born on Nov 15th, 2018, and currently weighs 8kg. She is neutered and she has tried to escape 2 times.
   - Animal: His name is Pikachu. He was born on Jan 7th, 2021, and currently weighs 15.04kg. He was not neutered and he has tried to escape once.
   - Animal: Her name is Devimon. She was born on May 12th, 2017, and currently weighs 11kg. She is neutered and she has tried to escape 5 times.
   
- Write queries for the following quests:
  - Find all animals whose name ends in "mon".
    
 ![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/d078c778-c73e-41f3-a0d1-45fa04475d81)

  - List the name of all animals born between 2016 and 2019.
   
![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/fd060b51-708b-4148-9a01-3205c986a515)

  - List the name of all animals that are neutered and have less than 3 escape attempts.
  
![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/354b8bec-66f7-4e1f-93e7-55d3c9c00498)

  - List the date of birth of all animals named either "Agumon" or "Pikachu".
  
![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/ed6485e7-180e-44b1-a053-023d43362ba6)

  - List name and escape attempts of animals that weigh more than 10.5kg
  
![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/cd0187ab-c0f0-4494-be44-83ba81035b89)

  - Find all animals that are neutered.
  
![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/0d910889-4d4d-4f50-a409-a8ded1d85ed3)

  - Find all animals not named Gabumon.
  
![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/d839d3b8-6262-4bc9-afbc-ecbbe89cba85)

  - Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)
  
![image](https://github.com/shihabrafio/Vet-Clinic/assets/67557999/ab182d0d-1a5e-4b45-9293-712f7cef8dfc)

2023-07-10 17:24 UTC, Gambit142 requested changes
Hi @shihabrafio 👋, 

Good job so far!

## Highlights
- Everything that creates or changes the structure of the table is in the schema.sql file.
- Everything that populates tables with data is in the data.sql file.
- Everything that is a query that helps to analyze data is in the queries.sql file.

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-07-10 17:24 UTC, Gambit142 commented on README.md
- [ ] Kindly include a valid LICENSE link to the LICENSE section in your README file. When I click the link, it displays a 404 error page. Adding an open-source license to your repository ensures that others can use, copy, modify, and contribute back to your project. It's an important step when creating an open-source project. 😎

2023-07-10 17:35 UTC, binhussen approved these changes
Hi @shihabrafio , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Created schema, data, and queries ✔️
- Well Structured Query ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-10 17:36 UTC, merged

2023-07-12 08:51 UTC, shella12 reviewed
Hi @shihabrafio, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Wrote required queries ✔️ 
- Created animal table ✔️ 
- Inserted required data ✔️ 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._